#!/bin/bash

# Exit-codes:
EXIT_SUCCESS=0
EXIT_HELP=1
EXIT_ERROR=2

# Global variables:
SOURCES="https://github.com/bibelwort/db_app/archive/refs/heads/main.zip"
WORKDIR="$( readlink -e "$( dirname "$0" )" )"
LOCAL_DB_DIR=""
LOCAL_APP_LOG="${WORKDIR}/app.log"

function print_error () {
	echo -e "\nERROR! \t$1"
}


function check_error () {
	if [[ "$1" != "0" ]]; then
		print_error "$2"
		exit ${EXIT_ERROR}
	fi
}


function print_help () {
	echo -e "\n$( basename ${0} ):"
	echo -e "\nDeploy db_app"
	
	echo -e "\nUSAGE:"
	echo -e "\t$( basename ${0} ) [OPTIONS]"

	echo -e "\nOPTIONS:"
	echo -e "\t--db <dirname>\t- DB data directory (default: ./data)"
	echo -e "\t--help         \t- Print this message\n"
	exit ${EXIT_HELP}
}


function make_dbdir () {
	# Make a directory for the DB
    
    if [[ ! -d "${LOCAL_DB_DIR}" ]]; then
		mkdir -p "${LOCAL_DB_DIR}"
        check_error "$?" "Cannot create directory '${LOCAL_DB_DIR}'"
	fi
}


function create_local_log_file () {
    if [[ ! -f "${LOCAL_APP_LOG}" ]]; then
		touch "${LOCAL_APP_LOG}"
        check_error "$?" "Cannot create output-file '${LOCAL_APP_LOG}'"
	fi
}


function download_sources () {
	# Download source from the GitHub repository
	if [[ -f app.py ]] && [[ -f Dockerfile ]]; then
        return
    fi
	
	wget -q "${SOURCES}"
	check_error "$?" "Cannot download sources"
	
	unzip -q "./main.zip"
	check_error "$?" "Cannot unzip file 'main.zip'"
	
	cp -r ./db_app-main/* ./ && \
        rm -rf ./db_app-main && \
        rm -f main.zip
}


function create_local_env_file () {
	env_file="${WORKDIR}/.env"
	if [[ -f "${env_file}" ]]; then
        rm -f "${env_file}"
        check_error "$?" "Cannot remove existing '.env' file"
    fi
	
	touch "${env_file}"
    check_error "$?" "Cannot create '.env' file"
    echo "LOCAL_DB_DIR=\"${LOCAL_DB_DIR}\"" &> "${env_file}"
    echo "LOCAL_APP_LOG=\"${LOCAL_APP_LOG}\"" &>> "${env_file}"
}


function main () {
	cd "${WORKDIR}"
    while [[ -n "$1" ]]; do
		case $1 in
		--db )
			shift
			LOCAL_DB_DIR="$1"
		;;
		--help )
			print_help
		;;
		* )
			print_error "Unknown parameter '$1'"
			print_help
		esac
		shift
	done
	
	if [[ -z "${LOCAL_DB_DIR}" ]]; then
		LOCAL_DB_DIR="${WORKDIR}/data"
	fi
    
    make_dbdir
    create_local_log_file
	download_sources
    create_local_env_file
    
    docker-compose up --detach
}

##############################################################################
main "$@"
exit ${EXIT_SUCCESS}
